spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/1
    username: 1
    password: 1
  jpa:
    hibernate:
      ddl-auto: create-drop